# Site settings
title: Felix' Homepage
email: mail@felixdoering.com
description: > # this means to ignore newlines until "baseurl:"
  Meine Seite, mein Blog. Hier möchte ich über mich erzählen.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://felixdoering.com" # the base hostname & protocol for your site
github_username:  h4llow3En
quick_view_length: 300
paginate: 5

# Build settings
markdown: kramdown
kramdown:
  input: GFM

sass:
  style: :compressed

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      category: blog
  -
    scope:
      path: ""
      type: "legal"
    values:
      layout: "default"

collections:
  projects:
    output: true
  legal:
    output: true
  quick_facts:

analytics :
  provider : google
  google :
      tracking_id : 'UA-63707835-1'
